name: wps-office-multilang
version: '10.1.0.6757-multilang'
summary:  WPS Office Suite with support for many languages
description: |
   ABOUT WPS OFFICE
   WPS Office, is an office productivity suite. WPS Office including Writer, Presentation and Spreadsheets, is a powerful office suite, which is able to process word file, produce wonderful slides, and analyse data as well. It is deeply compatible with all of the latest Microsoft Office file formats. It can easily open and read the documents created with Microsoft Office. This is the Linux version.
   Website: http://wps-community.org

   ABOUT THIS PACKAGE
   This is a multilanguge snap package for wps-office. It contains all interface languages available for the Windows version.
   This package ist based on the wps-office-all-lang-no-internet package and the official wps-office package.
   The official wps-office can be found at https://snapcraft.io/wps-office.
   The package wps-office-all-lang-no-internet can be found at https://snapcraft.io/wps-office-all-lang-no-internet or https://github.com/cyrpaut/wps-office-all-lang-no-internet.
   Because of security and privacy this package is shipped without internet plug. So there is no risk of a backdoor.
   
   This package can be found at https://github.com/HoLuLuLu/wps-office-multilang
   
   SUPPORTED INTERFACE LANGUAGES
   - Chinese (CN)
   - English (GB, US)
   - French (CA, FR)
   - German (DE)
   - Indonesian (ID)
   - Polish (PL)
   - Portuguese (BR, PT)
   - Russian (RU)
   - Spanish (ES, MX)
   
   SUPPORTED SPELLCHECK LANGUAGES
   - Catalan (ES)
   - Croatian (HR)
   - Czech (CZ)
   - Dutch (NL)
   - English (AU, GB, US)
   - French (FR)
   - Greek (GR)
   - German (DE)
   - Italian (IT)
   - Khmer (KH)
   - Lithuanian (LT)
   - Polish (PL)
   - Portuguese (BR, PT)
   - Romanian (RO)
   - Russian (RU)
   - Slovak (SK)
   - Spanish (ES, MX)
   - Swedish (SE)
   - Turkish (TR)
   - Ukrainian (UA)

architectures:
- amd64
confinement: strict
grade: stable
icon: gui/icon.png

parts:
  wps-office-multilang:
    source: ./wps-office-bin/
    plugin: dump
    stage-packages: [libpng16-16]

apps:
  et:
    command: usr/bin/et
    desktop: gui/et.desktop
    plugs:
    - alsa
    - cups-control
    - desktop
    - gsettings
    - home
    - opengl
    - pulseaudio
    - removable-media
    - unity7
    - wayland
    - x11
  wpp:
    command: usr/bin/wpp
    desktop: gui/wpp.desktop
    plugs:
    - alsa
    - cups-control
    - desktop
    - gsettings
    - home
    - opengl
    - pulseaudio
    - removable-media
    - unity7
    - wayland
    - x11
  wps:
    command: usr/bin/wps
    desktop: gui/wps.desktop
    plugs:
    - alsa
    - cups-control
    - desktop
    - gsettings
    - home
    - opengl
    - pulseaudio
    - removable-media
    - unity7
    - wayland
    - x11
